service: next-serverless-poc

provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless
  stage: ${env:NODE_ENV}
  region: us-east-1

functions:
  server:
    handler: index.server
    events:
      - http:
          method: get
